# Generated by Django 4.2.22 on 2025-06-09 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import logistics.custom_validator
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('domain', models.CharField(max_length=100, validators=[logistics.custom_validator.DomainNameValidator()], verbose_name='Domain')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active ?')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='admin', max_length=30, verbose_name='Role')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked ?')),
                ('failed_orders_count', models.PositiveIntegerField(default=0, verbose_name='Failed Orders Count')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.company', verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active ?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference Code')),
                ('quantity', models.PositiveIntegerField(validators=[logistics.custom_validator.PositiveValueValidator()], verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=30, verbose_name='Status')),
                ('has_been_processed', models.BooleanField(default=False, verbose_name='Has Been Processed ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.profile', verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=30, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='File')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.company', verbose_name='Company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.profile', verbose_name='Requested By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('domain'), name='unique_lower_domain', violation_error_message='Company with this domain already exists.'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='unique_name_domain'),
        ),
    ]
