services:
  web:
    build: .
    command: bash -c "mkdir -p /app/staticfiles && mkdir -p /app/media && chmod -R 755 /app/staticfiles /app/media && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A logistics worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles/
      - ./media:/app/media/
    depends_on:
      - web

volumes:
  postgres_data:
